spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:9090/realms/medicinaviva-realm
                    jwk-set-uri: http://localhost:9090/realms/medicinaviva-realm/protocol/openid-connect/certs

