INSERT INTO t_specialties (name, description, is_active)
VALUES
    ('Alergologia', NULL, TRUE),
    ('Anestesiologia', NULL, TRUE),
    ('Angiologia', NULL, TRUE),
    ('Bucomaxilofacial', NULL, TRUE),
    ('Cardiologia', NULL, TRUE),
    ('Cirurgia Cardiovascular', NULL, TRUE),
    ('Cirurgia de Cabeça e Pescoço', NULL, TRUE),
    ('Cirurgia Geral', NULL, TRUE),
    ('Cirurgia Pediátrica', NULL, TRUE),
    ('Cirurgia Plástica', NULL, TRUE),
    ('Cirurgia Torácica', NULL, TRUE),
    ('Clínica Médica', NULL, TRUE),
    ('Coloproctologia', NULL, TRUE),
    ('Dermatologia', NULL, TRUE),
    ('Endocrinologia', NULL, TRUE),
    ('Gastroenterologia', NULL, TRUE),
    ('Geriatria', NULL, TRUE),
    ('Ginecologia e Obstetrícia', NULL, TRUE),
    ('Hematologia e Hemoterapia', NULL, TRUE),
    ('Infectologia', NULL, TRUE),
    ('Medicina de Família e Comunidade', NULL, TRUE),
    ('Medicina do Trabalho', NULL, TRUE),
    ('Medicina Intensiva', NULL, TRUE),
    ('Medicina Nuclear', NULL, TRUE),
    ('Medicina Preventiva e Social', NULL, TRUE),
    ('Nefrologia', NULL, TRUE),
    ('Neurocirurgia', NULL, TRUE),
    ('Neurologia', NULL, TRUE),
    ('Oftalmologia', NULL, TRUE),
    ('Otorinolaringologia', NULL, TRUE),
    ('Pediatria', NULL, TRUE),
    ('Pneumologia', NULL, TRUE),
    ('Psiquiatria', NULL, TRUE),
    ('Radiologia e Diagnóstico por Imagem', NULL, TRUE),
    ('Reumatologia', NULL, TRUE),
    ('Urologia', NULL, TRUE),
    ('Cirurgia do Aparelho Digestivo', NULL, TRUE),
    ('Cirurgia do Trauma', NULL, TRUE),
    ('Cirurgia Vascular', NULL, TRUE),
    ('Endocrinologia Pediátrica', NULL, TRUE),
    ('Fisiatria', NULL, TRUE),
    ('Medicina do Esporte', NULL, TRUE),
    ('Medicina do Tráfego', NULL, TRUE),
    ('Medicina Legal', NULL, TRUE),
    ('Medicina Veterinária', NULL, TRUE),
    ('Medicina Integrativa', NULL, TRUE),
    ('Medicina Tradicional Chinesa', NULL, TRUE),
    ('Oncologia Clínica', NULL, TRUE),
    ('Oncologia Pediátrica', NULL, TRUE),
    ('Patologia', NULL, TRUE),
    ('Pneumologia Pediátrica', NULL, TRUE),
    ('Radioterapia', NULL, TRUE),
    ('Reumatologia Pediátrica', NULL, TRUE),
    ('Cirurgia Pediátrica', NULL, TRUE);